USE master;
GO

-- Xóa Database cũ nếu đã tồn tại để làm mới hệ thống
IF EXISTS (SELECT 1 FROM sys.databases WHERE name = N'QLSVNhom')
BEGIN
    ALTER DATABASE QLSVNhom SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLSVNhom;
END
GO

-- Tạo mới Database
CREATE DATABASE QLSVNhom;
GO

USE QLSVNhom;
GO

-- Thiết lập Master Key để hỗ trợ mã hóa dữ liệu
IF NOT EXISTS (SELECT 1 FROM sys.symmetric_keys WHERE name = N'##MS_DatabaseMasterKey##')
BEGIN
    CREATE MASTER KEY ENCRYPTION BY PASSWORD = N'DatabaseMasterKeyPassword123!';
END
GO

-- Bảng NHANVIEN: Lưu trữ thông tin nhân viên, lương (mã hóa RSA) và mật khẩu (Hash SHA1)
CREATE TABLE NHANVIEN (
    MANV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20) NULL,
    LUONG VARBINARY(MAX) NULL,
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,
    PUBKEY VARCHAR(20) NOT NULL
);
GO

-- Bảng LOP: Lưu trữ thông tin lớp học và nhân viên chủ nhiệm
CREATE TABLE LOP (
    MALOP VARCHAR(20) PRIMARY KEY,
    TENLOP NVARCHAR(100) NOT NULL,
    MANV VARCHAR(20) NOT NULL,
    CONSTRAINT FK_LOP_NHANVIEN FOREIGN KEY (MANV) REFERENCES NHANVIEN (MANV)
);
GO

-- Bảng SINHVIEN: Lưu trữ thông tin sinh viên và mật khẩu (Hash SHA1)
CREATE TABLE SINHVIEN (
    MASV VARCHAR(20) PRIMARY KEY,
    HOTEN NVARCHAR(100) NOT NULL,
    NGAYSINH DATETIME NULL,
    DIACHI NVARCHAR(200) NULL,
    MALOP VARCHAR(20) NOT NULL,
    TENDN NVARCHAR(100) NOT NULL UNIQUE,
    MATKHAU VARBINARY(MAX) NOT NULL,
    CONSTRAINT FK_SINHVIEN_LOP FOREIGN KEY (MALOP) REFERENCES LOP (MALOP)
);
GO

-- Bảng HOCPHAN: Lưu trữ danh mục các học phần
CREATE TABLE HOCPHAN (
    MAHP VARCHAR(20) PRIMARY KEY,
    TENHP NVARCHAR(100) NOT NULL,
    SOTC INT NULL
);
GO

-- Bảng BANGDIEM: Lưu trữ điểm thi đã được mã hóa RSA
CREATE TABLE BANGDIEM (
    MASV VARCHAR(20) NOT NULL,
    MAHP VARCHAR(20) NOT NULL,
    DIEMTHI VARBINARY(MAX) NULL,
    CONSTRAINT PK_BANGDIEM PRIMARY KEY (MASV, MAHP),
    CONSTRAINT FK_BANGDIEM_SINHVIEN FOREIGN KEY (MASV) REFERENCES SINHVIEN (MASV),
    CONSTRAINT FK_BANGDIEM_HOCPHAN FOREIGN KEY (MAHP) REFERENCES HOCPHAN (MAHP)
);
GO